AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  JotSyncFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.11
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource:
                - "*"
  EventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Invokes JotSync Python"
      ScheduleExpression: "rate(1 hour)"
      State: "ENABLED"
      Targets:
        - Arn:
            Fn::GetAtt:
              - "JotSyncFunction"
              - "Arn"
          Id: Id92e3c11c-80b0-40d4-a9af-234f68c1bbeb
  EventBridgeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref JotSyncFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - "EventRule"
          - "Arn"
